### ISSUE TITLE
Hello! My grandson has downloaded a computer application called "hubert virus" and now he cannot connect to us through skype. Can you help me, gentlemen?

### ISSUE THREAD

**Issue by ghost** [The-Hubert/The-Hubert#1]
# h

**Comment by Maxi2601** [comment]
use the for extra Hubert™

**Comment by ghost** [comment]
`>` Ok I will,

- [x] **__**

# [`>`](url) # young man.

**Comment by ghost** [comment]
### _**My grandson just connected to me and my husband on skype! Thank you kind sir for your help™️!**_
